### ISSUE TITLE
[Server] MissingQueryString rejection for empty query which is not required

### ISSUE THREAD

**Issue by guymguym** [awslabs/smithy-rs#1011] opened 2021-12-29 09:47 UTC
When generating codegen-server for S3, the ListObjects operation fails with MissingQueryString rejection when no search query is specified in the uri, but it does work with empty search term (just by adding an ending `?`). 

This operation input has members with the `smithy.api#httpQuery` trait,  but none of them is required, so I don't think this should fail when the search query is missing because it is a valid request uri AFAIK.

WDYT @crisidev @david-perez 

```
$ curl -X GET http://127.0.0.1:3333/lala
Expected query string in URI but none found

$ curl -X GET http://127.0.0.1:3333/lala?
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></ListBucketResult>
```

The rejection itself originates from here:
https://github.com/awslabs/smithy-rs/blob/b828dc80feddfa23bca904ddf1f1de2cd7a6f441/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpProtocolGenerator.kt#L674

**Comment by crisidev** [comment] 2021-12-29 11:53
You are probably right, this shouldn't fail as it does. @david-perez is working on some protocol tests to catch bugs the recent implementation of httpQuery trait.

**Comment by david-perez** [comment] 2021-12-29 15:44
@guymguym Thanks for reporting this. This is indeed a bug and at the moment I think that [your fix](https://github.com/s3d-rs/smithy-rs/commit/b5ccdde6e5ab89f955fb3eee32344eb039db1a51):

```rust
let query_string = request.uri().query().unwrap_or("");
```

will be the best we can do in the near future.

If we go for the "more correct" approach of rejecting requests that don't have a query string when the operation's input has a field with `@httpQuery` **and** `@required`, we should be consistent and _also_ reject requests whose body does not contain a field that is modeled with `@required` (or if the field is `null`).

At the moment the latter is not happening, we are instead defaulting to `None`. This is because we're sharing the deserialization code with the one used in the client for response deserialization, and in Smithy 1.0 [_removing_ `@required` is a backwards-compatible change](https://awslabs.github.io/smithy/1.0/guides/evolving-models.html?highlight=backwards#updating-structures), hence why [everything is an `Option`](https://github.com/awslabs/aws-sdk-rust/issues/327) that defaults to `None` if not present.

@rcoh I think we should deviate from the client here and start being more strict. Since _adding_ `@required` is **not** backwards-compatible, the server should be OK if it rejects requests that don't contain fields marked `@required`, wherever they are bound to, right?

**Comment by rcoh** [comment] 2021-12-30 14:44
Yeah that's correct, the server is free to respect `@required`. We may eventually want to even generate non-optional types for the server but that needs some guidance from the Smithy team

**Comment by guymguym** [comment] 2022-01-19 19:29
Hey @david-perez 
How would you suggest that I make a PR on that?
I would like to get my fix upstream somehow if possible.
Should I make a server config option to skip the query check and leave the current behaviour as default?
Or do you have new thoughts on this?
Thanks

**Comment by david-perez** [comment] 2022-01-20 11:17
@guymguym 

> How would you suggest that I make a PR on that?
> I would like to get my fix upstream somehow if possible.

If you want to contribute a PR with your one-line fix:

```rust
let query_string = request.uri().query().unwrap_or("");
```

that is certainly welcome and we will merge it, since it's an improvement over the current behavior, and would close this issue.

> Should I make a server config option to skip the query check and leave the current behaviour as default?

No, the current behavior is wrong.

---

Note that with your fix, another problem still remains. If `httpQuery` targets a shape member that is also `required`, the query deserialization logic will simply bind `None` to it and the request will go through.

This is of course incorrect, and we could fix it with an if statement, but its root cause is a larger one, namely, that we are generating Rust `Option`s for shape members that are not `required`. As mentioned above, this is because we borrow code from the AWS Rust SDK generation. This other issue should hence be tackled at this level. We talked yesterday to the Smithy team and we can and should indeed fix this in the server implementation. @crisidev is currently working on it, and we're tracking it over at https://github.com/awslabs/smithy-rs/issues/1095.

**Comment by guymguym** [comment] 2022-01-20 11:23
Thanks @david-perez! I will make a PR just to clear it off my hacks list.

**Closed** 2022-01-20 12:26 UTC
Labels: bug, server
